### ISSUE TITLE
Unable to create a JOB PR

### ISSUE THREAD

**Issue by mrister** [crocoder-dev/monorepo#343]
I was not able to create PR for the job posting because I was not able to push anything.
Do I need a fork or something?

```code
Please make sure you have the correct access rights
and the repository exists.
22:38:22.676: [monorepo] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/ae_networks-senior-js-developer-in-qa-automation:ae_networks-senior-js-developer-in-qa-automation --set-upstream
ERROR: Permission to crocoder-dev/monorepo.git denied to mrister.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
22:40:53.752: [monorepo] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/ae_networks-senior-js-developer-in-qa-automation:ae_networks-senior-js-developer-in-qa-automation --set-upstream
ERROR: Permission to crocoder-dev/monorepo.git denied to mrister.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```

**Comment by davidabram** [comment]
We haven't properly updated our tutorial how to create PR. You will need to fork our repo, create a jobpost markdown file and then create a PR to our repo. 

I have sent you an email to your public email, so you can send me the jobpost markdown there if you are in hurry to publish the job posting.

We are working on the new, correct tutorial that we will post [here](https://www.notion.so/crocoderdev/How-To-Post-A-Job-6e83b577dc1f4a4ba440a4538a0d6db8).

**Comment by danicapivalicaabram** [comment]
@mrister Sorry about the mix-up! Based on your feedback, we've updated the post accordingly.
As @davidabram mentioned, you can read the updated version [here](https://www.notion.so/crocoderdev/How-To-Post-A-Job-6e83b577dc1f4a4ba440a4538a0d6db8). 
I will close the task and thank you for your feedback :smiley:
